name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Multi line
      run: |
        npm -v
        node -v
        nuget -v
      
    - name: echo a string
      run: echo "Hello World"
